/// Flutter icons MtgIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MtgIcons
///      fonts:
///       - asset: fonts/MtgIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MtgIcons {
  MtgIcons._();

  static const _kFontFam = 'MtgIcons';
  static const String? _kFontPkg = null;

  static const IconData commander = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData energy = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData experience = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData health = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poison = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablelayoutallaround = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tablelayoutsameside = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rad = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
